### ISSUE TITLE
When to use "channel consenter add" and how to use helpers

### ISSUE THREAD

**Issue by nkaramolegos** [kfsoftware/hlf-operator#66]
Hello again, I have two questions:
1) If I create 3 orderer nodes from the begining of the deployment should I use the `kubectl hlf channel consenter add ` to add them to consenters? For example, in this [tutorial](https://github.com/kfsoftware/meetup-k8s-hlf#add-them-as-consenters) I can see that only the `ordnode-2` and `ordnode-3` are added to consenters. Thus I understand that the first one (i.e ordnode-1) is already consenter. Correct? Why is that?
2) How can I use the helpers command of plugin?

**Comment by nkaramolegos** [comment]
3. If I need to create a second channel (i.e ch2) with the same peer orgs but with 3 new orderer peers. Should I create a new orderer org? Or I can somehow separate the orderer nodes that will join ch1 and orderer nodes that will join ch2? (even though all these nodes belong to the same org)

**Comment by dviejokfs** [comment]
Hi @nkaramolegos 
1 - 
Consenter add should be used to modify the channel by adding more orderers, this is the case when you want to expand the network from, for example, 3 to 5 orderers.

When the channel is first created, the initial consenter set is defined.

2 -

I think the best option is to just copy/paste the code into your own project, since right now the helpers are only accessible by the kubecl plugin

3 - 
No, you can reuse the orderer org you already have and create multiple channels. Right now the kubectl-plugin doesn't have an option to specify the orderers when creating the channel, since all orderers that are in the cluster are added to the channel config for getting-started purposes, you can create an issue asking for this feature, it should be straight forward to implement (and this way we keep some orderliness :D )

**Comment by nkaramolegos** [comment]
Thank you. So for the third one the problem does not exist because I have one orderer org but exists due to the fact that for now all the available orderers nodes (of the cluster) are joining the new channels (as consenters too). Correct?

I will create any issue. Maybe a work around until this feature is added is to unjoin from the channel and delete the undesired ord-nodes from the consensus?

**Comment by dviejokfs** [comment]
When a node joins the channel, they're not consenters by default.

You need to add the orderer to the consenter set.

About specifying the orderers that belong to the channel, this was implemented in v1.6.0

https://github.com/hyperledger-labs/hlf-operator/blob/main/kubectl-hlf/cmd/channel/generate.go#L65-L75

Closing the issue, please open another issue in case there's any problem
