### ISSUE TITLE
For Standard Storage Class

### ISSUE THREAD

**Issue by levanthanh3005** [kfsoftware/hlf-operator#68]
First of all, thank you so much for your contribution to the community, this tool is really nice,
In my case, I setup Kubernetes in virtual machine (VM), and it does not have the standard storage class, the first error shows 'storageclass.storage.k8s.io "standard" not found',
After that, I tried to create a standard local storage class, but it still does not work:
"0/3 nodes are available: 3 node(s) didn't find available persistent volumes to bind."
I think the problem comes from the storage class, 
Could you please support me to make it run even with local storage,
Thank you

**Comment by dviejokfs** [comment]
Hi @levanthanh3005 

You would need to create a storage class and configure it when running the CA and Peer, if you're deploying it on-premise you would need to configure it for your environment: https://kubernetes.io/docs/concepts/storage/storage-classes/

I recommend you to start running in [KinD](https://github.com/kubernetes-sigs/kind) since a Kubernetes storage class is created by default.

**Comment by levanthanh3005** [comment]
Hi,
Thank you for your answer,
I dont want to run with KinD since, I have 3 VMs, and I want to run there,
I have a storage class like this:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

But the error is the same, CA can not find persistent volumes to bind,
Could you please support me to configure it,
Thank you

**Comment by dviejokfs** [comment]
@levanthanh3005 
Local storage would give you problems in the long run, since CAs and peers will only be able to run in the node it was provisioned.

I recommend you look at the options to centralize the storage:
https://kubernetes-csi.github.io/docs/drivers.html#production-drivers

I haven't tried local storage, but If the storage class is set up before creating the CAs, peers, and orderers, it should work.

Can you check the events of the persistent volume claim? It should give a hint why the storage provisioning is failing.

**Comment by dviejokfs** [comment]
I'm closing the issue as this seems related to the storage class in Kubernetes.

**Comment by k0ezeN** [comment]
Hey @levanthanh3005 , i am facing the same issue as you, did you find any solutions ?
